#define MEMORY_SIZE 1 << 16
#define REG_NUM 8
#define ADD_ADDI_STATIONS_NUM 3
#define LOAD_STATIONS_NUM 2
#define STORE_STATIONS_NUM 2
#define BEQ_STATIONS_NUM 1
#define JAL_RET_STATIONS_NUM 1
#define NEG_STATIONS_NUM 1
#define NOR_STATIONS_NUM 1
#define MULT_STATIONS_NUM 1